services:
  - type: web
    name: file-compressor-pro
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        value: 10000 